<template>
  <div class="space-y-6 pb-12">
    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
      <div>
        <h1 class="text-2xl font-bold text-gray-900 tracking-tight">Manage Transactions</h1>
        <p class="text-gray-500 mt-1 text-sm">Monitor all bookings and payment statuses across the platform.</p>
      </div>
      <div class="flex items-center gap-3">
        <!-- Transactions are generated by users booking tickets -->
      </div>
    </div>

    <!-- Table Card -->
    <UCard class="ring-1 ring-gray-100 rounded-2xl shadow-sm" :ui="{ body: '!p-0' }">
      <UTable :columns="columns" :rows="tableRows" :ui="{ td: 'whitespace-nowrap transition-colors hover:bg-gray-50/50' }">
        <template #createdAt-cell="{ row }">
          <div class="flex flex-col">
            <span class="font-medium text-gray-900">{{ new Date(row.original.createdAt as string).toLocaleDateString('id-ID', { dateStyle: 'medium' }) }}</span>
            <span class="text-xs text-gray-500">{{ new Date(row.original.createdAt as string).toLocaleTimeString('id-ID', { timeStyle: 'short' }) }}</span>
          </div>
        </template>
        <template #customerName-cell="{ row }">
          <div class="flex flex-col">
            <span class="font-medium text-gray-900">{{ row.original.customerName }}</span>
            <span class="text-xs text-gray-500">{{ row.original.email }}</span>
          </div>
        </template>
        <template #amount-cell="{ row }">
          <span class="font-semibold text-gray-900">Rp {{ (row.original.amount as number).toLocaleString() }}</span>
        </template>
        <template #status-cell="{ row }">
          <UBadge :color="row.original.status === 'PAID' ? 'success' : (row.original.status === 'PENDING' ? 'warning' : 'error')" variant="subtle" size="sm">
            {{ row.original.status }}
          </UBadge>
        </template>
        <template #actions-cell="{ row }">
          <div class="flex gap-2">
            <UButton size="sm" color="neutral" variant="ghost" icon="i-lucide-eye" />
          </div>
        </template>
      </UTable>
    </UCard>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useMockDataStore } from '~/stores/mockData'

definePageMeta({ layout: 'admin' })

const store = useMockDataStore()

const columns = [
  { accessorKey: 'bookingCode', header: 'Booking Code' },
  { accessorKey: 'customerName', header: 'Customer' },
  { accessorKey: 'routeInfo', header: 'Route' },
  { accessorKey: 'amount', header: 'Amount' },
  { accessorKey: 'status', header: 'Status' },
  { accessorKey: 'createdAt', header: 'Date' },
  { accessorKey: 'actions', header: 'Actions' }
]

const tableRows = computed(() => {
  return store.transactions.map(transaction => {
    const details = store.getScheduleDetails(transaction.scheduleId)
    return {
      ...transaction,
      routeInfo: details?.route ? `${details.route.originCity} → ${details.route.destinationCity}` : 'Unknown'
    }
  }).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
})
</script>
