### Admin Login
# @name login
POST http://localhost:8081/api/admin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}

### Get All Routes
GET http://localhost:8081/api/admin/routes
Authorization: Bearer {{login.response.body.data.token}}

### Create a Route
POST http://localhost:8081/api/admin/routes
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
  "origin_city": "Jakarta",
  "origin_pool": "Pool Kebon Jeruk",
  "destination_city": "Bandung",
  "destination_pool": "Pool Pasteur"
}

### Update a Route
PUT http://localhost:8081/api/admin/routes/ed488e3c-cc61-47dd-84d8-b81b35e71890
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
  "origin_city": "Jakarta",
  "origin_pool": "Pool Kebon Jeruk Baru 2",
  "destination_city": "Bandung",
  "destination_pool": "Pool Pasteur Baru"
}

### Delete a Route
DELETE http://localhost:8081/api/admin/routes/ed488e3c-cc61-47dd-84d8-b81b35e71890
Authorization: Bearer {{login.response.body.data.token}}

### Get All Fleets
GET http://localhost:8081/api/admin/fleets?page=1&limit=10
Authorization: Bearer {{login.response.body.data.token}}

### Create a Fleet
POST http://localhost:8081/api/admin/fleets
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
  "name": "Armada 1",
  "plate_number": "B 1234 XYZ",
  "type": "Premium",
  "total_seats": 14
}

### Update a Fleet
PUT http://localhost:8081/api/admin/fleets/9469132c-2dfa-4698-a23f-bc2a8bda933e
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
  "name": "Armada 1 Updated",
  "plate_number": "B 5678 ABC",
  "type": "Reguler",
  "total_seats": 16,
  "active_status": true
}

### Delete a Fleet
DELETE http://localhost:8081/api/admin/fleets/9469132c-2dfa-4698-a23f-bc2a8bda933e
Authorization: Bearer {{login.response.body.data.token}}
